"""Added tags for user

Revision ID: 6eafea36d253
Revises: 1004b1c70fde
Create Date: 2023-05-26 09:43:28.712416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6eafea36d253'
down_revision = '1004b1c70fde'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barsatag',
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['barsa.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['barsa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('barsa', 'gunlic')
    op.drop_column('barsa', 'crime')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('barsa', sa.Column('crime', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('barsa', sa.Column('gunlic', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('barsatag')
    # ### end Alembic commands ###
